package com.github.yusufyilmazfr.podcast4j.entity

data class Episode(
    val id: Long? = null,
    val title: String? = null,
    val link: String? = null,
    val description: String? = null,
    val guid: String? = null,
    val datePublished: Long? = null,
    val datePublishedPretty: String? = null,
    val dateCrawled: Long? = null,
    val enclosureUrl: String? = null,
    val enclosureType: String? = null,
    val enclosureLength: Int? = null,
    val duration: Int? = null,
    val explicit: Int? = null,
    val episode: Int? = null,
    val episodeType: String? = null,
    val season: Int? = null,
    val image: String? = null,
    val imageUrlHash: String? = null,
    val feedItunesId: Long? = null,
    val feedImage: String? = null,
    val feedImageUrlHash: String? = null,
    val feedId: Int? = null,
    val podcastGuid: String? = null,
    val feedUrl: String? = null,
    val feedAuthor: String? = null,
    val feedTitle: String? = null,
    val feedLanguage: String? = null,
    val feedDead: Int? = null,
    val feedDuplicateOf: String? = null,
    val chaptersUrl: String? = null,
    val transcriptUrl: String? = null,
    val value: Value? = null,
    val persons: MutableList<Person?>? = null,
    val transcripts: MutableList<Transcript?>? = null,
    val categories: MutableMap<Int?, String?>? = null,
)
